obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery.o
obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery_ttf.o
obj-$(CONFIG_OF)		+= sec_adc.o
obj-$(CONFIG_MULTI_CHARGING)	+= sec_multi_charger.o
obj-$(CONFIG_MULTI_PORT_CHARGING)	+= sec_multi_port_charger.o
obj-$(CONFIG_BATTERY_CISD)	+= sec_cisd.o
obj-$(CONFIG_BATTERY_NOTIFIER)	+= battery_notifier.o

obj-$(CONFIG_FUELGAUGE_S2MU004)		+= s2mu004_fuelgauge.o

obj-$(CONFIG_CHARGER_BQ25898S)	+= bq25898s_charger.o
obj-$(CONFIG_CHARGER_S2MU004)   += s2mu004_charger.o
